### ISSUE TITLE
Fields with default values not saving properly

### ISSUE THREAD

**Issue by dougfir-lc** [noripyt/wagtail-react-streamfield#11]
When adding a field (such as a ChoiceBlock) that has a default value to a page
the default value appears in the field (visually) but is not set when the page is saved.
This causes a validation error as no value is being set.

**Version:** 0.8.5

**Steps to Reproduce:**
1. Create new page and add a block (ChoiceBlock or CharBlock in this case) that contains a default value.
2. Save the page.

**Result:** A validation error occurs on the field.

**Expected Result:** The page saves with the default value in the field.

**Workaround:** Select different value in choices and the reselect default value. Page then saves without error.

Here is a sample of the code used to recreate this issue:
```python
class TestStreamBlock(StreamBlock):
    NUMBERS = (('one', 'one'), ('two', 'two'),)

    time = TimeBlock()
    name = CharBlock(default='Test Name 1')
    number = ChoiceBlock(max_length=3, choices=NUMBERS, default=NUMBERS[0])

class TestPage(Page):
    content = StreamField(TestStreamBlock(required=False),blank=True)

    content_panels = Page.content_panels + [
        StreamFieldPanel('content'),
    ]
```

**Comment by Henv** [comment]
Same issue on my side. Although the default values are shown on the inputs, once you save, the request data is sent with null on those fields. 
The same case was possibly happening on this [invalid PR from react-streamfield](https://github.com/noripyt/react-streamfield/pull/2)
The workaround works, but is extremely annoying when you have many choices with a default value.

**Comment by Henv** [comment]
Found another thing today related to this, if you use a `BooleanBlock` with a default value of True it also doesn't save the field.

**Comment by roelio** [comment]
I also encountered this problem and currently use a workaround for the `BooleanBlock` problem: 
```
const event = new Event('change');
Array.from(document.querySelectorAll('input')).forEach(elm => {
  elm.dispatchEvent(event)
})
```
Probably something similar can be used for choice fields.
This code should be run each time a `BooleanBlock` is added in the edit page. Not very nice, but for now it works.

**Comment by BertrandBordage** [comment]
Fixed by 154a4bf69ed2ac84a518c6f3268997be6a5aa4fc.
@dougfir-lc @Henv @evanwinter @roelio Please test that it correctly fixed your use case.
On my setup everything is fixed, even when using an HTML default value in a `RichTextBlock`, like `'<strong>Hello!</strong>'` :smile:

**Comment by BertrandBordage** [comment]
Forgot to mention that it’s released in 0.8.6.

**Comment by Henv** [comment]
Hey @BertrandBordage I've tested the version 0.8.6 and the defaults that I had all seem to work fine :) Thanks for this update.

**Comment by dougfir-lc** [comment]
@BertrandBordage - The fix worked nicely for most of the blocks but it seems that `ChoiceBlock` is still having some trouble for us. The field now comes up blank instead of showing the default and upon inspection it seem that the entire tuple is being inserted as the default value.  

Error Message:
Select a valid choice. ['one', 'one'] is not one of the available choices

**Comment by BertrandBordage** [comment]
@dougfir-lc Could you please share a minimal example yielding this error?

**Comment by dougfir-lc** [comment]
```python
class TestStreamBlock(StreamBlock):
    NUMBERS = (('one', 'one'), ('two', 'two'),)

    number = ChoiceBlock(max_length=3, choices=NUMBERS, default=NUMBERS[0])

class TestPage(Page):
    content = StreamField(TestStreamBlock(required=False),blank=True)

    content_panels = Page.content_panels + [
        StreamFieldPanel('content'),
    ]
```

**Comment by BertrandBordage** [comment]
@dougfir-lc That’s what I thought, you’re passing a tuple as a default value in `ChoiceBlock`. It should be `default=NUMBERS[0][0]`. I’m surprised that it was working before! It should not work with a Django field as far as I know, so it’s a bug in Wagtail if it was working.
